apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube
  template:
    metadata:
      labels:
        app: kube
    spec:
      containers:
      - name: kube
        image: midianet/kube:1.0.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kube
spec:
  type: NodePort
  selector:
    app: kube
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
